
test_mode: 0

reads_dir: "/media/kishonylab/KishonyStorage/noga/MaccabiUTI/Mathews_processing/Filtered_data/"

wd: ""

global_name: "Sample_Maccabi_Ecoli_SeqPlate"

priority_samples_file: "database/cluster_cases.txt"

same_strain_file: "/media/kishonylab/KishonyStorage/noga/Dropbox/Noga/MaccabiUTI/scripts/input_instructions/All_same_strain_pairs.xlsx"

test_group: {1051011:['13_D7', '25_A9', '10_F7'], 3213554: ['5_B1', '5_A11', '5_A12']}

