
test_mode: 0

reads_dir: "/media/kishonylab/KishonyStorage/noga/MaccabiUTI/Mathews_processing/Filtered_data/"

wd: ""

global_name: "Sample_Maccabi_Ecoli_SeqPlate"

priority_samples_file: "workflow/config/cluster_cases.txt"

same_strain_file: "/media/kishonylab/KishonyStorage/noga/Dropbox/Noga/MaccabiUTI/scripts/input_instructions/All_same_strain_pairs.xlsx"
same_strain_output: "workflow/config/samples_to_process.csv"

test_group: {1051011:['13_D7', '25_A9', '10_F7'], 3213554: ['5_B1', '5_A11', '5_A12']}

unicycler:
  threads: 1
  keep: 0

bowtie2_build_pangenome:
  extra: ""
  threads: 1

bowtie2_pangenome:
  extra: ""
  threads: 1

breseq:
  priority: 50
  threads: 1

mpileup_pangenome:
  extra: "-d 10000"

prokka:
  coverage: 1
  evalue: 1e-06
  threads: 1

roary:
  identity: 95
  threads: 10

samtools_index_pangenome:
  threads: 1
  extra: ""

samtools_sort_pangenome:
  extra: ""
  tmpdir: "/tmp/"
  threads: 1

split_seq:
  length: 20

bwa_mem2_mem:
  sort: "samtools"
  sort_order: "coordinate"
  threads: 1